import "./style.css"
import type { Metadata } from 'next'
import NavBar from '@/src/components/NavBar/NavBar'
import { ReduxProvider } from '@/src/redux/provider'
import SideBar from "./SideBar";
import TopNav from "./TopNav";
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ReduxProvider>
    <html lang="en">
      <head>
      </head>
      <body >
      <div className="DoctorProfile-body">
        <SideBar />
        <div className="DoctorProfile-main">
          <TopNav />
          <div style={{display:"flex"}}>
          </div>
          {children}
        </div>
      </div>
      </body >
    </html>
    </ReduxProvider>
  )
}
